version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mytest
      MYSQL_DATABASE: nycab
    ports:
      - 3306:3306
    volumes:
      - "${DBDIR}:/var/lib/mysql"
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379