// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CabPickupsCount cab pickups count
// swagger:model cabPickupsCount
type CabPickupsCount struct {

	// found times in query
	Count int64 `json:"count,omitempty"`

	// does this car exist
	Found bool `json:"found,omitempty"`

	// car id
	Medallion string `json:"medallion,omitempty"`
}

// Validate validates this cab pickups count
func (m *CabPickupsCount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CabPickupsCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CabPickupsCount) UnmarshalBinary(b []byte) error {
	var res CabPickupsCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
