// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CabPickupsCount cab pickups count
// swagger:model cabPickupsCount
type CabPickupsCount struct {

	// found times in query
	// Required: true
	Count *int64 `json:"count"`

	// does this car exist
	// Required: true
	Found *bool `json:"found"`

	// car id
	// Required: true
	Medallion *string `json:"medallion"`
}

// Validate validates this cab pickups count
func (m *CabPickupsCount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFound(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMedallion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CabPickupsCount) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("count", "body", m.Count); err != nil {
		return err
	}

	return nil
}

func (m *CabPickupsCount) validateFound(formats strfmt.Registry) error {

	if err := validate.Required("found", "body", m.Found); err != nil {
		return err
	}

	return nil
}

func (m *CabPickupsCount) validateMedallion(formats strfmt.Registry) error {

	if err := validate.Required("medallion", "body", m.Medallion); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CabPickupsCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CabPickupsCount) UnmarshalBinary(b []byte) error {
	var res CabPickupsCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
