// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi nycab
No description


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0
    Contact:

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
