// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "No description",
    "title": "nycab",
    "contact": {},
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/cabs/pickups/count": {
      "get": {
        "description": "Query how many trips a particular cab (medallion) has made given a particular pickup date.",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "name": "medallions",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "name": "date",
            "in": "query",
            "required": true
          },
          {
            "type": "boolean",
            "default": false,
            "description": "Enforce to get latest data, NOT from cache.",
            "name": "refresh",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/getCabsPickupsCountResponse"
            }
          }
        }
      }
    },
    "/cabs/pickups/count/cache": {
      "delete": {
        "description": "Method to clear the cache",
        "parameters": [
          {
            "type": "string",
            "format": "date",
            "description": "Clear from date inclusive",
            "name": "startDate",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "Clear to date inclusive",
            "name": "endDate",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "cabPickupsCount": {
      "type": "object",
      "properties": {
        "count": {
          "description": "found times in query",
          "type": "integer"
        },
        "found": {
          "description": "does this car exist",
          "type": "boolean"
        },
        "medallion": {
          "description": "car id",
          "type": "string"
        }
      }
    },
    "errResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "getCabsPickupsCountResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "result": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/cabPickupsCount"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "No description",
    "title": "nycab",
    "contact": {},
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/cabs/pickups/count": {
      "get": {
        "description": "Query how many trips a particular cab (medallion) has made given a particular pickup date.",
        "parameters": [
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "name": "medallions",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "name": "date",
            "in": "query",
            "required": true
          },
          {
            "type": "boolean",
            "default": false,
            "description": "Enforce to get latest data, NOT from cache.",
            "name": "refresh",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/getCabsPickupsCountResponse"
            }
          }
        }
      }
    },
    "/cabs/pickups/count/cache": {
      "delete": {
        "description": "Method to clear the cache",
        "parameters": [
          {
            "type": "string",
            "format": "date",
            "description": "Clear from date inclusive",
            "name": "startDate",
            "in": "query"
          },
          {
            "type": "string",
            "format": "date",
            "description": "Clear to date inclusive",
            "name": "endDate",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  },
  "definitions": {
    "cabPickupsCount": {
      "type": "object",
      "properties": {
        "count": {
          "description": "found times in query",
          "type": "integer"
        },
        "found": {
          "description": "does this car exist",
          "type": "boolean"
        },
        "medallion": {
          "description": "car id",
          "type": "string"
        }
      }
    },
    "errResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "getCabsPickupsCountResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "result": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/cabPickupsCount"
          }
        }
      }
    }
  }
}`))
}
