# @name getPickupCount
GET http://localhost:10086/v1/cabs/pickups/count?date=2019-01-01&medallions=123,456,789 http/2.0

###

# @name deleteCache
DELETE http://localhost:10086/v1/cabs/pickups/count/cache?startDate=2019-10-10&endDate=2019-11-11 http/2.0