// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetCabsPickupsCountURL generates an URL for the get cabs pickups count operation
type GetCabsPickupsCountURL struct {
	Date       strfmt.Date
	Medallions []string
	Refresh    *bool

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetCabsPickupsCountURL) WithBasePath(bp string) *GetCabsPickupsCountURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetCabsPickupsCountURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetCabsPickupsCountURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/cabs/pickups/count"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	date := o.Date.String()
	if date != "" {
		qs.Set("date", date)
	}

	var medallionsIR []string
	for _, medallionsI := range o.Medallions {
		medallionsIS := medallionsI
		if medallionsIS != "" {
			medallionsIR = append(medallionsIR, medallionsIS)
		}
	}

	medallions := swag.JoinByFormat(medallionsIR, "")

	if len(medallions) > 0 {
		qsv := medallions[0]
		if qsv != "" {
			qs.Set("medallions", qsv)
		}
	}

	var refresh string
	if o.Refresh != nil {
		refresh = swag.FormatBool(*o.Refresh)
	}
	if refresh != "" {
		qs.Set("refresh", refresh)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetCabsPickupsCountURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetCabsPickupsCountURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetCabsPickupsCountURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetCabsPickupsCountURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetCabsPickupsCountURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetCabsPickupsCountURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
